<?php

return [
	'PAGINATE_USER' => 10,
	'PAGINATE_USER_TRASH' => 10,
	'PAGINATE_COMPANY' => 10,
	'PAGINATE_COMPANY_TRASH' => 10,
	'PAGINATE_CATEGORY_PLAN' => 10,
	'PAGINATE_CATEGORY_PLAN_TRASH' => 10,
	'PAGINATE_PLAN' => 10,
	'PAGINATE_PLAN_TRASH' => 10,
	'PAGINATE_RIDER' => 10,
	'PAGINATE_RIDER_TRASH' => 10,
	'PAGINATE_PFR' => 10,
];
